spring.application.name=ShopShavvy

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT secret key
security.jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration-time.accessToken=${JWT_EXPIRATION_TIME_ACCESS_TOKEN}
jwt.expiration-time.refreshToken=${JWT_EXPIRATION_TIME_REFRESH_TOKEN}
jwt.expiration-time.activationToken=${JWT_EXPIRATION_TIME_ACTIVATION_TOKEN}
jwt.expiration-time.resetPasswordToken=${JWT_EXPIRATION_TIME_RESET_PASSWORD_TOKEN}

# Mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SUPPORT_EMAIL}
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.config.import=optional:file:.env[.properties]


logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.storage.base-path=/home/manvi/Documents/Shop-Shavvy
spring.web.resources.static-locations=file:/home/manvi/Documents/Shop-Shavvy/